/* eslint-disable @typescript-eslint/no-explicit-any */
import type { ExchangeConnector } from './index';import { safeFetchJson } from '../utils/safeFetch';import { mapInterval } from '../utils/intervals';
const F={rate:null,nextFundingTime:null,bias:"UNKNOWN" as const}; const OI={value:null,changePct:null,bias:"UNKNOWN" as const}; const LS={ratio:null,longPct:null,shortPct:null,bias:"UNKNOWN" as const};
export const bitgetConnector: ExchangeConnector={
async getCandles(symbol,interval,limit){const r=await safeFetchJson<any>(`https://api.bitget.com/api/v2/mix/market/candles?symbol=${symbol}&productType=USDT-FUTURES&granularity=${mapInterval('bitget',interval)}&limit=${Math.min(limit,1000)}`); if(!r.ok) return []; return (r.data.data||[]).map((x:string[])=>({time:Number(x[0]),open:Number(x[1]),high:Number(x[2]),low:Number(x[3]),close:Number(x[4]),volume:Number(x[5]||0)||null}));},
async getPrice(symbol){const r=await safeFetchJson<any>(`https://api.bitget.com/api/v2/mix/market/ticker?symbol=${symbol}&productType=USDT-FUTURES`);return r.ok?Number((Array.isArray(r.data.data)?r.data.data[0]:r.data.data)?.lastPr):null;},async getMarkPrice(symbol){const r=await safeFetchJson<any>(`https://api.bitget.com/api/v2/mix/market/ticker?symbol=${symbol}&productType=USDT-FUTURES`);return r.ok?Number((Array.isArray(r.data.data)?r.data.data[0]:r.data.data)?.markPrice):null;},
async getOrderBook(symbol,limit){const r=await safeFetchJson<any>(`https://api.bitget.com/api/v2/mix/market/merge-depth?symbol=${symbol}&productType=USDT-FUTURES&limit=${limit}`);if(!r.ok) return null; const d=r.data.data||{}; return {bids:(d.bids||[]).map((x:string[])=>({price:Number(x[0]),size:Number(x[1])})),asks:(d.asks||[]).map((x:string[])=>({price:Number(x[0]),size:Number(x[1])})),timestamp:Date.now()};},
async getFunding(symbol){const r=await safeFetchJson<any>(`https://api.bitget.com/api/v2/mix/market/current-fund-rate?symbol=${symbol}&productType=USDT-FUTURES`); if(!r.ok) return F; return {rate:Number(r.data.data?.fundingRate??null),nextFundingTime:Number(r.data.data?.nextSettleTime??null),bias:'UNKNOWN'};},
async getOpenInterest(symbol){const r=await safeFetchJson<any>(`https://api.bitget.com/api/v2/mix/market/open-interest?symbol=${symbol}&productType=USDT-FUTURES`); if(!r.ok) return OI; return {value:Number(r.data.data?.openInterestList?.[0]?.size??r.data.data?.openInterest??null),changePct:null,bias:'UNKNOWN'};},async getOpenInterestHistory(){return [];},
async getRecentTrades(symbol,limit){const r=await safeFetchJson<any>(`https://api.bitget.com/api/v2/mix/market/fills?symbol=${symbol}&productType=USDT-FUTURES&limit=${Math.min(limit,200)}`);if(!r.ok)return []; return (r.data.data||[]).map((t:any)=>({id:t.tradeId,time:Number(t.ts),price:Number(t.price),size:Number(t.size),side:t.side==='buy'?'buy':t.side==='sell'?'sell':'unknown'}));},
async getLongShortRatio(){return LS;}
};
