export const SMART_FIB_DEFAULTS = {
  // Swing Engine
  swingPivotLeft: 5,
  swingPivotRight: 5,
  useAutoTfSwingProfile: true,
  autoTfSensitivity: "Balanced" as "Fast" | "Balanced" | "Slow",
  useAutoAnchorTF: true,
  anchorTfMode: "HigherTF" as "HigherTF" | "LowerTF",
  anchorRescueMode: "Disabled" as "Disabled" | "Enabled",
  useSwingAtrFilter: true,
  atrLength: 14,
  minSwingAtr: 0.5,
  usePairAtrFilter: true,
  minPairAtrDistance: 1.0,
  showSwingLabels: true,
  showOnlyActiveSwingPair: true,
  showSwingConnector: true,
  protectDominantSwingMap: true,
  mapReplaceFactor: 0.7,
  expireOldMap: true,
  maxMapAgeBars: 200,
  mapFarPct: 0.1,
  enableSwingFallback: true,
  fallbackMaxHistory: 10,
  fallbackOnlyBeyondBrokenSwing: true,
  fallbackCreateBoxes: true,
  enableBrokenEdgeRollover: true,
  rolloverConfirmBars: 3,
  rolloverCreateBoxes: true,
  maxSwingLabels: 2,
  swingHighColor: "#00FF00",
  swingLowColor: "#FF0000",

  // Fib Map Engine
  showFib: true,
  fibExtendMode: "FixedBars" as "FixedBars" | "Dynamic",
  fibFixedBars: 50,
  labelMode: "All" as "All" | "KeyOnly" | "None",
  fibLabelOffset: 5,
  fibLabelSize: 10,
  showLevelQualityOnLabels: true,
  invalidateOnSwingBreak: true,
  invalidationAtrBuffer: 0.1,

  // Fib Levels
  fibLevels: [
    { value: 0.0, name: "Swing Edge", show: true, color: "#FFFFFF", width: 1, style: "solid" as "solid" | "dashed" },
    { value: 0.236, name: "Early Reaction", show: true, color: "#888888", width: 1, style: "solid" },
    { value: 0.382, name: "TP Layer", show: true, color: "#AAAAAA", width: 1, style: "solid" },
    { value: 0.5, name: "Mid Target", show: true, color: "#CCCCCC", width: 1, style: "solid" },
    { value: 0.618, name: "Early 0.618", show: true, color: "#FFFF00", width: 1, style: "solid" },
    { value: 0.65, name: "Early 0.65", show: true, color: "#FFFF88", width: 1, style: "solid" },
    { value: 0.786, name: "Deep Reaction", show: true, color: "#FF8800", width: 2, style: "solid" },
    { value: 0.882, name: "Sniper Gold", show: true, color: "#00FF00", width: 3, style: "solid" },
    { value: 0.941, name: "Second Gold", show: true, color: "#00FFFF", width: 3, style: "solid" },
    { value: 1.0, name: "Swing Edge", show: true, color: "#FFFFFF", width: 1, style: "solid" },
    { value: 1.236, name: "Extended", show: false, color: "#888888", width: 1, style: "dashed" },
    { value: 1.272, name: "Extended", show: false, color: "#888888", width: 1, style: "dashed" },
    { value: 1.348, name: "Extended", show: false, color: "#888888", width: 1, style: "dashed" },
    { value: 1.424, name: "Extended", show: false, color: "#888888", width: 1, style: "dashed" },
    { value: 1.618, name: "Extended", show: false, color: "#888888", width: 1, style: "dashed" },
  ],

  // Level Power Engine
  touchMode: "ATR Tolerance" as "Exact Touch" | "ATR Tolerance" | "Percent Tolerance" | "Tick Tolerance",
  touchAtrTol: 0.1,
  touchPctTol: 0.05,
  touchTickTol: 0.01,
  minWickRatio: 0.3,
  minBodyRatio: 0.5,
  moveAwayAtrMult: 1.5,
  confirmOnClose: true,
  approachLookback: 5,
  maxChopCandles: 3,
  sweepLookback: 10,
  useSweepScore: true,

  // Box Engine
  enableBoxes: true,
  boxSourceMode: "SwingBased" as "SwingBased" | "FibBased",
  boxSearchBars: 20,
  baseClusterBars: 5,
  maxBoxes: 5,
  extendBoxesRight: true,
  deleteInvalidBoxes: true,
  fadeTestedBoxes: true,
  keepUntouchedHistorical: false,
  clearOldBoxesOnNewMap: true,
  keepOnlyActiveMapBoxes: true,
  boxInvalidationMode: "SwingBreak" as "SwingBreak" | "TimeBased",
  consumeAfterTouches: 3,
  minBarsBetweenTouches: 5,
  useVolBoxScore: false,
  removeBoxOnMitigation: true,
  boxMitigationPercent: 0.5,
  useWickForMitigation: true,
  demandFill: "rgba(0,255,0,0.1)",
  demandBorder: "#00FF00",
  supplyFill: "rgba(255,0,0,0.1)",
  supplyBorder: "#FF0000",
  boxTextColor: "#FFFFFF",
  boxTextSize: 10,

  // EMA Confluence
  showEma: true,
  enableEmaConfluence: true,
  emaLen1: 21,
  emaLen2: 50,
  emaLen3: 200,
  emaDistanceAtrTol: 0.05,
  useEmaTrendFilter: true,

  // HTF Alignment
  enableHTF: true,
  htf1: "4h",
  htf2: "1d",
  htf3: "1w",
  conflictPenalty: 20,

  // Entry Decision Engine
  enableEarlyEntries: true,
  enableDeepEntries: true,
  enableSniperEntries: true,
  enableSecondGoldEntries: true,
  minScoreEarly: 60,
  minScoreDeep: 75,
  minScoreSniper: 90,
  minScoreSecondGold: 90,
  entryTriggerMode: "Touch" as "Touch" | "Confirm" | "Break",
  oneSignalPerFibMap: true,
  cooldownBars: 10,
  showEntryLabels: true,
  maxSignalLabels: 3,

  // Trade Visual Engine
  showTradeVisuals: true,
  slMode: "ATR" as "ATR" | "Fixed" | "Percent",
  slAtrBuffer: 1.0,
  projectionBars: 50,
  showRRBoxes: true,
  entryLineColor: "#FFFFFF",
  slLineColor: "#FF0000",
  tpLineColor: "#00FF00",
  riskBoxColor: "rgba(255,0,0,0.2)",
  rewardBoxColor: "rgba(0,255,0,0.2)",
  tradeLineWidth: 2,
  tradeLineStyle: "solid" as "solid" | "dashed",

  // Dashboard
  showDashboard: true,
};